{% set name = "sagemaker-jupyterlab-extension" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1ec771e3632f82e66988c38859bff716f6c1eb2d199b1fad928ad6454e55274d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - sagemaker-jupyterlab-extension-common
    - async-lru
    - aws-embedded-metrics

test:
  imports:
    - sagemaker_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab workspace primary extension module
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nileshvd
    - zuoyuanh
