{% set name = "sagemaker-jupyterlab-extension" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 43028fd5ef7a0ccc392ff6688ee591fe67432e13d1276a3293a9832558176bdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >=3.9
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - sagemaker-jupyterlab-extension-common
    - jupyterlab-git >=0.51.1,<1.0.0
    - async-lru
    - aws-embedded-metrics

test:
  imports:
    - sagemaker_jupyterlab_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab workspace primary extension module
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gogakoreli
    - gkoreli
    - nileshvd
    - zuoyuanh
